In [1]:
import pandas as pd

df=pd.read_csv('AUDIT_dataset - 1.csv')
df.head()

,Participant ID,How often do you have a drink containing alcohol?,How many standard drinks do you have on a typical drinking day?,How often do you have six or more drinks on one occasion?,How often do you find it hard to stop drinking once started?,How often do you fail to do what is expected due to drinking?,How often do you need a drink in the morning after heavy drinking?,How often do you feel guilt or remorse after drinking?,How often do you forget what happened because of drinking?,Have you or someone else been injured due to your drinking?,Has someone been concerned about your drinking or suggested cutting down?,Total Score,Level
0,008554f0-a4b8-46b2-b96d-41ba129874b8,Never,5 or 6,Daily or almost daily,Weekly,Less than monthly,Daily or almost daily,Daily or almost daily,Weekly,No,"Yes, during the past year",21,Alcohol Dependent
1,3cd46f5b-0fa0-4338-b1ce-9a92c533a87d,Never,5 or 6,Never,Monthly,Never,Less than monthly,Daily or almost daily,Monthly,No,"Yes, but not in the past year",11,Hazardous
2,a1f723c4-2c2c-4e0e-9842-2b539f8910ce,4 or more times a week,10 or more,Less than monthly,Daily or almost daily,Less than monthly,Weekly,Monthly,Never,"Yes, during the past year","Yes, during the past year",19,Alcohol Dependent
3,82060640-e700-4e43-9539-1c0d487398cc,2-4 times a month,5 or 6,Less than monthly,Daily or almost daily,Weekly,Less than monthly,Monthly,Daily or almost daily,"Yes, during the past year","Yes, during the past year",19,Alcohol Dependent
4,1be7ebab-17cc-4990-a5d7-ae61c121b54f,Never,5 or 6,Never,Daily or almost daily,Weekly,Less than monthly,Weekly,Weekly,No,No,16,Alcohol Dependent

In [2]:
df.drop('Participant ID', axis=1, inplace=True)
df.head()

,How often do you have a drink containing alcohol?,How many standard drinks do you have on a typical drinking day?,How often do you have six or more drinks on one occasion?,How often do you find it hard to stop drinking once started?,How often do you fail to do what is expected due to drinking?,How often do you need a drink in the morning after heavy drinking?,How often do you feel guilt or remorse after drinking?,How often do you forget what happened because of drinking?,Have you or someone else been injured due to your drinking?,Has someone been concerned about your drinking or suggested cutting down?,Total Score,Level
0,Never,5 or 6,Daily or almost daily,Weekly,Less than monthly,Daily or almost daily,Daily or almost daily,Weekly,No,"Yes, during the past year",21,Alcohol Dependent
1,Never,5 or 6,Never,Monthly,Never,Less than monthly,Daily or almost daily,Monthly,No,"Yes, but not in the past year",11,Hazardous
2,4 or more times a week,10 or more,Less than monthly,Daily or almost daily,Less than monthly,Weekly,Monthly,Never,"Yes, during the past year","Yes, during the past year",19,Alcohol Dependent
3,2-4 times a month,5 or 6,Less than monthly,Daily or almost daily,Weekly,Less than monthly,Monthly,Daily or almost daily,"Yes, during the past year","Yes, during the past year",19,Alcohol Dependent
4,Never,5 or 6,Never,Daily or almost daily,Weekly,Less than monthly,Weekly,Weekly,No,No,16,Alcohol Dependent

In [3]:
df.rename(columns={'How often do you have a drink containing alcohol?': 'Q1', 'How many standard drinks do you have on a typical drinking day?': 'Q2' , 'How often do you have six or more drinks on one occasion?':'Q3'
                  ,'How often do you find it hard to stop drinking once started?':'Q4','How often do you fail to do what is expected due to drinking?':'Q5',
                  'How often do you need a drink in the morning after heavy drinking?':'Q6','How often do you feel guilt or remorse after drinking?':'Q7',
                  'How often do you forget what happened because of drinking?':'Q8','Have you or someone else been injured due to your drinking?':'Q9','Has someone been concerned about your drinking or suggested cutting down?':'Q10'}, inplace=True)

In [4]:
df.head()

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Total Score,Level
0,Never,5 or 6,Daily or almost daily,Weekly,Less than monthly,Daily or almost daily,Daily or almost daily,Weekly,No,"Yes, during the past year",21,Alcohol Dependent
1,Never,5 or 6,Never,Monthly,Never,Less than monthly,Daily or almost daily,Monthly,No,"Yes, but not in the past year",11,Hazardous
2,4 or more times a week,10 or more,Less than monthly,Daily or almost daily,Less than monthly,Weekly,Monthly,Never,"Yes, during the past year","Yes, during the past year",19,Alcohol Dependent
3,2-4 times a month,5 or 6,Less than monthly,Daily or almost daily,Weekly,Less than monthly,Monthly,Daily or almost daily,"Yes, during the past year","Yes, during the past year",19,Alcohol Dependent
4,Never,5 or 6,Never,Daily or almost daily,Weekly,Less than monthly,Weekly,Weekly,No,No,16,Alcohol Dependent

In [5]:
df.isna().sum()

Q1             0
Q2             0
Q3             0
Q4             0
Q5             0
Q6             0
Q7             0
Q8             0
Q9             0
Q10            0
Total Score    0
Level          0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Q1           5000 non-null   object
 1   Q2           5000 non-null   object
 2   Q3           5000 non-null   object
 3   Q4           5000 non-null   object
 4   Q5           5000 non-null   object
 5   Q6           5000 non-null   object
 6   Q7           5000 non-null   object
 7   Q8           5000 non-null   object
 8   Q9           5000 non-null   object
 9   Q10          5000 non-null   object
 10  Total Score  5000 non-null   int64
 11  Level        5000 non-null   object
dtypes: int64(1), object(11)
memory usage: 468.9+ KB

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Q1']=le.fit_transform(df['Q1'])
df['Q2']=le.fit_transform(df['Q2'])
df['Q3']=le.fit_transform(df['Q3'])
df['Q4']=le.fit_transform(df['Q4'])
df['Q5']=le.fit_transform(df['Q5'])
df['Q6']=le.fit_transform(df['Q6'])
df['Q7']=le.fit_transform(df['Q7'])
df['Q8']=le.fit_transform(df['Q8'])
df['Q9']=le.fit_transform(df['Q9'])
df['Q10']=le.fit_transform(df['Q10'])

In [8]:
df.head()

   Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  Q10  Total Score              Level
0   4   3   0   4   1   0   0   4   0    2           21  Alcohol Dependent
1   4   3   3   2   3   1   0   2   0    1           11          Hazardous
2   2   1   1   0   1   4   2   3   2    2           19  Alcohol Dependent
3   1   3   1   0   4   1   2   0   2    2           19  Alcohol Dependent
4   4   3   3   0   4   1   4   4   0    0           16  Alcohol Dependent

In [9]:
df['Level']=le.fit_transform(df['Level'])
df.head()

   Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  Q10  Total Score  Level
0   4   3   0   4   1   0   0   4   0    2           21      0
1   4   3   3   2   3   1   0   2   0    1           11      1
2   2   1   1   0   1   4   2   3   2    2           19      0
3   1   3   1   0   4   1   2   0   2    2           19      0
4   4   3   3   0   4   1   4   4   0    0           16      0

In [10]:
db=df.copy()
db.head()

   Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  Q10  Total Score  Level
0   4   3   0   4   1   0   0   4   0    2           21      0
1   4   3   3   2   3   1   0   2   0    1           11      1
2   2   1   1   0   1   4   2   3   2    2           19      0
3   1   3   1   0   4   1   2   0   2    2           19      0
4   4   3   3   0   4   1   4   4   0    0           16      0

In [11]:
db.drop('Total Score', axis=1, inplace=True)

In [12]:
db.head()

   Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  Q10  Level
0   4   3   0   4   1   0   0   4   0    2      0
1   4   3   3   2   3   1   0   2   0    1      1
2   2   1   1   0   1   4   2   3   2    2      0
3   1   3   1   0   4   1   2   0   2    2      0
4   4   3   3   0   4   1   4   4   0    0      0

In [13]:
from sklearn.model_selection import train_test_split
x=db[['Q1','Q2','Q3','Q4','Q5','Q6','Q7','Q8','Q9','Q10']]
y=db['Level']
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,shuffle=True)

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# SVM model training
svm_model = SVC(kernel='linear')  # You can try different kernels ('linear', 'rbf', 'poly', etc.)
svm_model.fit(xtrain, ytrain)


predictions = svm_model.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
report = classification_report(ytest, predictions)

print(f"Accuracy: {accuracy}")
print(f"Classification Report:\n{report}")

Accuracy: 0.663
Classification Report:
              precision    recall  f1-score   support

           0       0.66      1.00      0.80       663
           1       0.00      0.00      0.00       316
           2       0.00      0.00      0.00        21

    accuracy                           0.66      1000
   macro avg       0.22      0.33      0.27      1000
weighted avg       0.44      0.66      0.53      1000

C:\Users\Navyashri\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Navyashri\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Navyashri\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [15]:
svm = SVC(C=100, gamma=0.1)

svm.fit(xtrain, ytrain)

# Make predictions on the test/validation set
predictions = svm.predict(xtest)

# Evaluate the model's performance
accuracy = accuracy_score(ytest, predictions)
print(f"Accuracy on Test/Validation Set: {accuracy:.4f}")

Accuracy on Test/Validation Set: 0.7390

In [16]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import make_scorer, accuracy_score

# Define the SVM model
svm = SVC()

# Define the hyperparameters and their values for tuning
param_grid = {
    'C': [0.1, 1, 10, 100],  
    'gamma': [0.1, 1, 10]    
}

# scoring metric
scorer = make_scorer(accuracy_score)

# GridSearchCV
grid_search = GridSearchCV(estimator=svm, param_grid=param_grid, scoring=scorer, cv=3)
grid_result = grid_search.fit(xtrain, ytrain)

# Get the best parameters and best score
best_params = grid_result.best_params_
best_score = grid_result.best_score_

print("Best Parameters:", best_params)
print("Best Accuracy:", best_score)

Best Parameters: {'C': 1, 'gamma': 0.1}
Best Accuracy: 0.7717461599282879

In [17]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)  # You can set different hyperparameters here
dt_model.fit(xtrain, ytrain)

# Model evaluation
predictions = dt_model.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
report = classification_report(ytest, predictions)

print(f"Accuracy: {accuracy}")
print(f"Classification Report:\n{report}")

Accuracy: 0.74
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.79      0.82       663
           1       0.58      0.65      0.61       316
           2       0.30      0.43      0.35        21

    accuracy                           0.74      1000
   macro avg       0.58      0.62      0.60      1000
weighted avg       0.75      0.74      0.75      1000

In [18]:
from sklearn.model_selection import GridSearchCV


param_grid = {
    'max_depth': [None, 5, 10, 15],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2']
}


dt = DecisionTreeClassifier(random_state=42)


grid_search = GridSearchCV(estimator=dt, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(xtrain, ytrain)

best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

predictions = best_model.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
report = classification_report(ytest, predictions)

print(f"Best Parameters: {best_params}")
print(f"Accuracy: {accuracy}")
print(f"Classification Report:\n{report}")

Best Parameters: {'max_depth': None, 'max_features': 'auto', 'min_samples_leaf': 4, 'min_samples_split': 10}
Accuracy: 0.751
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.85      0.83       663
           1       0.61      0.58      0.59       316
           2       0.83      0.24      0.37        21

    accuracy                           0.75      1000
   macro avg       0.75      0.55      0.60      1000
weighted avg       0.75      0.75      0.75      1000

In [19]:
# Mentioning class weights
class_weights = {0:1,1: 1,2: 5} 

#  Decision Tree classifier with class weights
dt = DecisionTreeClassifier(random_state=42, class_weight=class_weights)


dt.fit(xtrain, ytrain)
predictions = dt.predict(xtest)
accuracy = accuracy_score(ytest, predictions)
report = classification_report(ytest, predictions)

print(f"Accuracy: {accuracy}")
print(f"Classification Report:\n{report}")

Accuracy: 0.739
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.79      0.82       663
           1       0.58      0.66      0.62       316
           2       0.27      0.14      0.19        21

    accuracy                           0.74      1000
   macro avg       0.56      0.53      0.54      1000
weighted avg       0.75      0.74      0.74      1000

In [20]:
from sklearn.ensemble import RandomForestClassifier


rf_model = RandomForestClassifier(n_estimators=100, random_state=42)  

rf_model.fit(xtrain, ytrain)

rf_predictions = rf_model.predict(xtest)

rf_accuracy = accuracy_score(ytest, rf_predictions)
rf_report = classification_report(ytest, rf_predictions)

print(f"Random Forest Accuracy: {rf_accuracy}")
print(f"Random Forest Classification Report:\n{rf_report}")

Random Forest Accuracy: 0.832
Random Forest Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.94      0.89       663
           1       0.78      0.66      0.71       316
           2       0.00      0.00      0.00        21

    accuracy                           0.83      1000
   macro avg       0.54      0.53      0.54      1000
weighted avg       0.81      0.83      0.82      1000

C:\Users\Navyashri\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Navyashri\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Navyashri\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [21]:
new_data=[[3,0,1,0,1,2,4,0,1,4]]
predicted_class = rf_model.predict(new_data)

print("Predicted Class:", predicted_class)

Predicted Class: [0]

C:\Users\Navyashri\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [22]:
new_data=[[0,0,0,0,1,2,0,0,1,0]]
predicted_class = rf_model.predict(new_data)

print("Predicted Class:", predicted_class)

Predicted Class: [0]

C:\Users\Navyashri\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [23]:
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, Dropout
# from tensorflow.keras.optimizers import Adam

# # Create a Sequential model
# model = Sequential()

# # Add input layer and hidden layers
# model.add(Dense(128, input_dim=xtrain.shape[1], activation='relu'))  # Adjust input_dim based on the number of features
# model.add(Dropout(0.2))  # Dropout layer for regularization
# model.add(Dense(64, activation='relu'))
# model.add(Dropout(0.2))

# # Output layer
# model.add(Dense(3, activation='softmax'))  # Assuming 3 classes for the output layer (adjust if needed)

# # Compile the model
# model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# # Train the model
# history = model.fit(xtrain, ytrain, epochs=20, batch_size=32, validation_data=(xtest, ytest))

# # Evaluate the model
# loss, accuracy = model.evaluate(xtest, ytest)
# print(f"Test Accuracy: {accuracy}")

In [24]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

# Initialize the Gaussian Naive Bayes classifier
nb_classifier = GaussianNB()

# Train the classifier
nb_classifier.fit(xtrain, ytrain)

# Predict on the test set
nb_predictions = nb_classifier.predict(xtest)

# Calculate accuracy
accuracy = accuracy_score(ytest, nb_predictions)
print(f"Naive Bayes Accuracy: {accuracy}")

# Generate classification report
report = classification_report(ytest, nb_predictions)
print(f"Classification Report:\n{report}")

Naive Bayes Accuracy: 0.726
Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.95      0.83       663
           1       0.65      0.29      0.41       316
           2       0.00      0.00      0.00        21

    accuracy                           0.73      1000
   macro avg       0.46      0.42      0.41      1000
weighted avg       0.70      0.73      0.68      1000

C:\Users\Navyashri\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Navyashri\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Navyashri\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [25]:
# from imblearn.over_sampling import RandomOverSampler
# from sklearn.naive_bayes import GaussianNB
# from sklearn.metrics import accuracy_score, classification_report

# # Apply oversampling to balance classes
# oversampler = RandomOverSampler(random_state=42)
# xtrain_resampled, ytrain_resampled = oversampler.fit_resample(xtrain, ytrain)

# # Initialize and train the Gaussian Naive Bayes classifier
# nb_classifier = GaussianNB()
# nb_classifier.fit(xtrain_resampled, ytrain_resampled)

# # Predict on the test set
# nb_predictions = nb_classifier.predict(xtest)

# # Calculate accuracy
# accuracy = accuracy_score(ytest, nb_predictions)
# print(f"Naive Bayes Accuracy with Oversampling: {accuracy}")

# # Generate classification report
# report = classification_report(ytest, nb_predictions)
# print(f"Classification Report:\n{report}")

In [26]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report

base_estimator = RandomForestClassifier(n_estimators=100, random_state=42)

adaboost_classifier = AdaBoostClassifier(base_estimator=base_estimator, n_estimators=50, random_state=42)

adaboost_classifier.fit(xtrain, ytrain)

adaboost_predictions = adaboost_classifier.predict(xtest)

accuracy = accuracy_score(ytest, adaboost_predictions)
print(f"AdaBoost with Random Forest Accuracy: {accuracy}")

report = classification_report(ytest, adaboost_predictions)
print(f"Classification Report:\n{report}")

AdaBoost with Random Forest Accuracy: 0.826
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.94      0.89       663
           1       0.76      0.65      0.70       316
           2       1.00      0.05      0.09        21

    accuracy                           0.83      1000
   macro avg       0.87      0.54      0.56      1000
weighted avg       0.83      0.83      0.81      1000

In [27]:
new_data=[[4,3,3,2,3,1,0,2,0,1]]
predicted_class = rf_model.predict(new_data)

print("Predicted Class:", predicted_class)

Predicted Class: [1]

C:\Users\Navyashri\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [28]:
new_data=[[4,3,3,4,4,1,4,2,4,1]]
predicted_class = rf_model.predict(new_data)

print("Predicted Class:", predicted_class)

Predicted Class: [0]

C:\Users\Navyashri\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [29]:
from joblib import dump

In [30]:
dump(rf_model, './../savedModels/rf_model.joblib')

['./../savedModels/rf_model.joblib']